import type { Theme } from "@opentype/shared";

export const DEFAULT_THEME_ID = "default-dark";

export const THEMES: Theme[] = [
  {
    id: "default-dark",
    name: "Default Dark",
    dark: true,
    colors: {
      "--bg-base": "#0f0f0f",
      "--bg-surface": "#161616",
      "--bg-elevated": "#212121",
      "--bg-border": "#1e1e1e",
      "--bg-border-strong": "#2a2a2a",
      "--text-primary": "#e2e8f0",
      "--text-secondary": "#d1d5db",
      "--text-muted": "#6b7280",
      "--text-faint": "#4b5563",
      "--text-ghost": "#374151",
      "--char-correct": "#e2e8f0",
      "--char-incorrect": "#ef4444",
      "--char-untyped": "#374151",
      "--accent": "#4f8ef7",
      "--accent-dim": "#1e3a5f",
    },
  },
  {
    id: "serika-dark",
    name: "Serika Dark",
    dark: true,
    colors: {
      "--bg-base": "#323437",
      "--bg-surface": "#2c2e31",
      "--bg-elevated": "#3a3c40",
      "--bg-border": "#26282b",
      "--bg-border-strong": "#4a4d51",
      "--text-primary": "#d1d0c5",
      "--text-secondary": "#b8b6ac",
      "--text-muted": "#646669",
      "--text-faint": "#4b4d50",
      "--text-ghost": "#3c3e41",
      "--char-correct": "#d1d0c5",
      "--char-incorrect": "#ca4754",
      "--char-untyped": "#4d4f53",
      "--accent": "#e2b714",
      "--accent-dim": "#5a4a0e",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    dark: true,
    colors: {
      "--bg-base": "#282a36",
      "--bg-surface": "#21222c",
      "--bg-elevated": "#44475a",
      "--bg-border": "#343746",
      "--bg-border-strong": "#6272a4",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#e6e6e6",
      "--text-muted": "#6272a4",
      "--text-faint": "#44475a",
      "--text-ghost": "#383a46",
      "--char-correct": "#f8f8f2",
      "--char-incorrect": "#ff5555",
      "--char-untyped": "#44475a",
      "--accent": "#ff79c6",
      "--accent-dim": "#5a2e4a",
    },
  },
  {
    id: "nord",
    name: "Nord",
    dark: true,
    colors: {
      "--bg-base": "#2e3440",
      "--bg-surface": "#3b4252",
      "--bg-elevated": "#434c5e",
      "--bg-border": "#2e3440",
      "--bg-border-strong": "#4c566a",
      "--text-primary": "#eceff4",
      "--text-secondary": "#e5e9f0",
      "--text-muted": "#81a1c1",
      "--text-faint": "#4c566a",
      "--text-ghost": "#3b4252",
      "--char-correct": "#d8dee9",
      "--char-incorrect": "#bf616a",
      "--char-untyped": "#4c566a",
      "--accent": "#88c0d0",
      "--accent-dim": "#2e4a5a",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    dark: true,
    colors: {
      "--bg-base": "#282828",
      "--bg-surface": "#1d2021",
      "--bg-elevated": "#3c3836",
      "--bg-border": "#1d2021",
      "--bg-border-strong": "#504945",
      "--text-primary": "#ebdbb2",
      "--text-secondary": "#d5c4a1",
      "--text-muted": "#a89984",
      "--text-faint": "#7c6f64",
      "--text-ghost": "#504945",
      "--char-correct": "#ebdbb2",
      "--char-incorrect": "#fb4934",
      "--char-untyped": "#504945",
      "--accent": "#fe8019",
      "--accent-dim": "#5a3a1a",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    dark: true,
    colors: {
      "--bg-base": "#282c34",
      "--bg-surface": "#21252b",
      "--bg-elevated": "#2c313c",
      "--bg-border": "#181a1f",
      "--bg-border-strong": "#3e4452",
      "--text-primary": "#abb2bf",
      "--text-secondary": "#9da5b4",
      "--text-muted": "#5c6370",
      "--text-faint": "#4b5263",
      "--text-ghost": "#3b4048",
      "--char-correct": "#abb2bf",
      "--char-incorrect": "#e06c75",
      "--char-untyped": "#4b5263",
      "--accent": "#61afef",
      "--accent-dim": "#2a3a4e",
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine",
    dark: true,
    colors: {
      "--bg-base": "#191724",
      "--bg-surface": "#1f1d2e",
      "--bg-elevated": "#26233a",
      "--bg-border": "#1f1d2e",
      "--bg-border-strong": "#393552",
      "--text-primary": "#e0def4",
      "--text-secondary": "#c8c4dc",
      "--text-muted": "#908caa",
      "--text-faint": "#6e6a86",
      "--text-ghost": "#403d52",
      "--char-correct": "#e0def4",
      "--char-incorrect": "#eb6f92",
      "--char-untyped": "#403d52",
      "--accent": "#ebbcba",
      "--accent-dim": "#4a3340",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    dark: true,
    colors: {
      "--bg-base": "#1e1e2e",
      "--bg-surface": "#181825",
      "--bg-elevated": "#313244",
      "--bg-border": "#181825",
      "--bg-border-strong": "#45475a",
      "--text-primary": "#cdd6f4",
      "--text-secondary": "#bac2de",
      "--text-muted": "#7f849c",
      "--text-faint": "#585b70",
      "--text-ghost": "#45475a",
      "--char-correct": "#cdd6f4",
      "--char-incorrect": "#f38ba8",
      "--char-untyped": "#45475a",
      "--accent": "#b4befe",
      "--accent-dim": "#3a3a5c",
    },
  },
  {
    id: "light",
    name: "Light",
    dark: false,
    colors: {
      "--bg-base": "#ffffff",
      "--bg-surface": "#f3f4f6",
      "--bg-elevated": "#e5e7eb",
      "--bg-border": "#e5e7eb",
      "--bg-border-strong": "#d1d5db",
      "--text-primary": "#1f2937",
      "--text-secondary": "#374151",
      "--text-muted": "#6b7280",
      "--text-faint": "#9ca3af",
      "--text-ghost": "#d1d5db",
      "--char-correct": "#1f2937",
      "--char-incorrect": "#ef4444",
      "--char-untyped": "#d1d5db",
      "--accent": "#2563eb",
      "--accent-dim": "#dbeafe",
    },
  },
  {
    id: "serika",
    name: "Serika",
    dark: false,
    colors: {
      "--bg-base": "#faf5e6",
      "--bg-surface": "#f0e9d2",
      "--bg-elevated": "#e6dec3",
      "--bg-border": "#e6dec3",
      "--bg-border-strong": "#c9bd9b",
      "--text-primary": "#323437",
      "--text-secondary": "#4a4c4f",
      "--text-muted": "#7c7e82",
      "--text-faint": "#939599",
      "--text-ghost": "#c9bd9b",
      "--char-correct": "#323437",
      "--char-incorrect": "#ca4754",
      "--char-untyped": "#939599",
      "--accent": "#e2b714",
      "--accent-dim": "#5a4a0e",
    },
  },
];
